package com.mod.mapper;

import org.apache.ibatis.annotations.Param;

import com.mod.bean.Orders;

public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Mon Nov 13 08:33:01 CST 2017
	 */
	int insert(Orders record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Mon Nov 13 08:33:01 CST 2017
	 */
	int insertSelective(Orders record);
	int updateByOUid(@Param("oid")String oid,@Param("uid")Integer uid);
	int updateByOUid(@Param("oid")Long oid,@Param("uid")Integer uid);
}