package com.mod.mapper;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.MapKey;
import org.apache.ibatis.annotations.Param;

import com.mod.bean.OrderForm;

public interface OrderFormMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderform
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	int insert(OrderForm record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orderform
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	int insertSelective(OrderForm record);

	LinkedList<HashMap<String, Object>> getOrderList(@Param("oid")Long oid,@Param("uid")Integer uid);
}