package com.mod.mapper;

import com.mod.bean.Orders;

public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Sat Nov 11 11:52:21 CST 2017
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Sat Nov 11 11:52:21 CST 2017
	 */
	int insertSelective(Orders record);
}