package com.mod.bean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class GoodsType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodstype.tid
	 * @mbggenerated  Thu Nov 23 15:42:31 CST 2017
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goodstype.tname
	 * @mbggenerated  Thu Nov 23 15:42:31 CST 2017
	 */
	private String tname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodstype.tid
	 * @return  the value of goodstype.tid
	 * @mbggenerated  Thu Nov 23 15:42:31 CST 2017
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodstype.tid
	 * @param tid  the value for goodstype.tid
	 * @mbggenerated  Thu Nov 23 15:42:31 CST 2017
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goodstype.tname
	 * @return  the value of goodstype.tname
	 * @mbggenerated  Thu Nov 23 15:42:31 CST 2017
	 */
	public String getTname() {
		return tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goodstype.tname
	 * @param tname  the value for goodstype.tname
	 * @mbggenerated  Thu Nov 23 15:42:31 CST 2017
	 */
	public void setTname(String tname) {
		this.tname = tname;
	}
}