package com.mod.bean;

public class GoodsWithBLOBs extends Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.imgPath
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    private String imgpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.filePath
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    private String filepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.imgPath
     *
     * @return the value of goods.imgPath
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.imgPath
     *
     * @param imgpath the value for goods.imgPath
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.filePath
     *
     * @return the value of goods.filePath
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.filePath
     *
     * @param filepath the value for goods.filePath
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
}