package com.mod.bean;

public class GoodsAndroidWithBLOBs extends GoodsAndroid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsand.imageUrl
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsand.banners
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    private String banners;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsand.imageUrl
     *
     * @return the value of goodsand.imageUrl
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsand.imageUrl
     *
     * @param imageurl the value for goodsand.imageUrl
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsand.banners
     *
     * @return the value of goodsand.banners
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public String getBanners() {
        return banners;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsand.banners
     *
     * @param banners the value for goodsand.banners
     *
     * @mbggenerated Fri Nov 17 16:21:49 CST 2017
     */
    public void setBanners(String banners) {
        this.banners = banners;
    }
}