package com.mod.bean;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.sql.Timestamp;
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderForm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.oid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private Long oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.gid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private Integer gid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.uid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.gnum
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private Integer gnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.date
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
	private Timestamp date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.state
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.realPrice
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private Double realprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderform.address
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.oid
	 * @return  the value of orderform.oid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public Long getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.oid
	 * @param oid  the value for orderform.oid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setOid(Long oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.gid
	 * @return  the value of orderform.gid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public Integer getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.gid
	 * @param gid  the value for orderform.gid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.uid
	 * @return  the value of orderform.uid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.uid
	 * @param uid  the value for orderform.uid
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.gnum
	 * @return  the value of orderform.gnum
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public Integer getGnum() {
		return gnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.gnum
	 * @param gnum  the value for orderform.gnum
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setGnum(Integer gnum) {
		this.gnum = gnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.date
	 * @return  the value of orderform.date
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public Timestamp getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.date
	 * @param date  the value for orderform.date
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setDate(Timestamp date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.state
	 * @return  the value of orderform.state
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.state
	 * @param state  the value for orderform.state
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.realPrice
	 * @return  the value of orderform.realPrice
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public Double getRealprice() {
		return realprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.realPrice
	 * @param realprice  the value for orderform.realPrice
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setRealprice(Double realprice) {
		this.realprice = realprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderform.address
	 * @return  the value of orderform.address
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderform.address
	 * @param address  the value for orderform.address
	 * @mbggenerated  Fri Nov 10 12:42:34 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}