package com.mod.bean;

public class Orders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.oid
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	private String oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.uid
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.state
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.sum
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	private Double sum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.address
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.oid
	 * @return  the value of orders.oid
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public String getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.oid
	 * @param oid  the value for orders.oid
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public void setOid(String oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.uid
	 * @return  the value of orders.uid
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.uid
	 * @param uid  the value for orders.uid
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.state
	 * @return  the value of orders.state
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.state
	 * @param state  the value for orders.state
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.sum
	 * @return  the value of orders.sum
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public Double getSum() {
		return sum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.sum
	 * @param sum  the value for orders.sum
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public void setSum(Double sum) {
		this.sum = sum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.address
	 * @return  the value of orders.address
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.address
	 * @param address  the value for orders.address
	 * @mbggenerated  Sat Nov 11 20:42:11 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}