package com.mod.bean;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Users {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uid
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uname
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String uname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.upwd
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String upwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.phone
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.city
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.regDate
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
	private Date regdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.idCard
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.realName
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.age
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.email
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.sex
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.avatar
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	private String avatar;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uid
	 * @return  the value of users.uid
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uid
	 * @param uid  the value for users.uid
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uname
	 * @return  the value of users.uname
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uname
	 * @param uname  the value for users.uname
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.upwd
	 * @return  the value of users.upwd
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getUpwd() {
		return upwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.upwd
	 * @param upwd  the value for users.upwd
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.phone
	 * @return  the value of users.phone
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.phone
	 * @param phone  the value for users.phone
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.city
	 * @return  the value of users.city
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.city
	 * @param city  the value for users.city
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.regDate
	 * @return  the value of users.regDate
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public Date getRegdate() {
		return regdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.regDate
	 * @param regdate  the value for users.regDate
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.idCard
	 * @return  the value of users.idCard
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.idCard
	 * @param idcard  the value for users.idCard
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.realName
	 * @return  the value of users.realName
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.realName
	 * @param realname  the value for users.realName
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.age
	 * @return  the value of users.age
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.age
	 * @param age  the value for users.age
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.email
	 * @return  the value of users.email
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.email
	 * @param email  the value for users.email
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.sex
	 * @return  the value of users.sex
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.sex
	 * @param sex  the value for users.sex
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.avatar
	 * @return  the value of users.avatar
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.avatar
	 * @param avatar  the value for users.avatar
	 * @mbggenerated  Fri Nov 17 16:22:42 CST 2017
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public Users() {
	}

	public Users(String uname, String upwd) {
		this.uname = uname;
		this.upwd = upwd;
	}
}